spring:
  mvc:
    contentnegotiation:
      favor-parameter: true
  jackson:
    date-format: dd.MM.yyyy HH:mm:ss
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
  data:
    rest:
      base-path: /api
  mustache:
    servlet:
      expose-request-attributes: true
  security:
    oauth2:
      client:
        registration:
          todo:
            client-id: ${oa2-client-id}
            client-secret: ${oa2-client-secret}
            client-name: ToDo App with GitHub Authentication
            provider: github
            scope: user
            redirect-uri: http://localhost:8080/login/oauth2/code/github