spring:
  mvc:
    contentnegotiation:
      favor-parameter: true
  jackson:
    date-format: dd.MM.yyyy HH:mm:ss
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
  data:
    rest:
      base-path: /api
  mustache:
    servlet:
      expose-request-attributes: true
todo:
  authentication:
    find-by-email-uri: ${authUri:http://localhost:8081/api/persons/search/findByEmailIgnoreCase?email=}
    username: ${authEmail:admin@example.com}
    password: ${authPass:admin}